version: '3.3'

services:
  web:
    build: .
    container_name: fintrak_image
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
  db:
    image: 'postgres:12'
    hostname: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine
    container_name: fintra_redis

  celery:
    build: .
    command: celery -A PROJECT.celery worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
  
  celery_beat:
    build: .
    command:
      [
        'celery',
        '--app=platform_api',
        'beat',
        '--scheduler=django_celery_beat.schedulers:DatabaseScheduler',
        '--loglevel=INFO',
      ]
    volumes:
      - ./:/app
    depends_on:
      - web
      - db
      - redis

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

