databases:
  - name: fintrakdb
    databaseName: fintrakdb
    user: fintrakdb_user

services:
  - type: web
    name: fintrak
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn PROJECT.wsgi:application"
    envVars:
      - key: $RENDER_POSTGRES_DB_URL
        fromDatabase:
          name: fintrakdb
          property: connectionString
      - key: $SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
