# Generated by Django 3.2.6 on 2021-09-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_totalbudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetexpense',
            name='income_date',
        ),
        migrations.RemoveField(
            model_name='budgetincome',
            name='income_date',
        ),
        migrations.AlterField(
            model_name='totalbudget',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
