# Generated by Django 3.2.6 on 2021-08-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_app', '0002_alter_income_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
